
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from '@/hooks/use-toast';

const SUPABASE_URL = "https://wdzlruiekcznbcicjgrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkemxydWlla2N6bmJjaWNqZ3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODAyNzYsImV4cCI6MjA1OTg1NjI3Nn0.NaoVf3tU3Xz08CWCHpQtq7_9H6G6ES9EjtCvPHa0aRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
  },
});

// Helper function for debugging Supabase responses
export const logSupabaseResponse = (action: string, data: any, error: any) => {
  if (error) {
    console.error(`Supabase ${action} error:`, error);
    toast({
      title: `Error with ${action}`,
      description: error.message || 'An unknown error occurred',
      variant: "destructive",
    });
    return false;
  }
  console.log(`Supabase ${action} successful:`, data);
  return true;
};

// Helper function to handle Supabase responses with UI notifications
export const handleSupabaseResponse = (action: string, data: any, error: any, showSuccess = true) => {
  if (error) {
    console.error(`Supabase ${action} error:`, error);
    toast({
      title: `Error with ${action}`,
      description: error.message || 'An unknown error occurred',
      variant: "destructive",
    });
    return { success: false, data: null, error };
  }
  
  console.log(`Supabase ${action} successful:`, data);
  
  if (showSuccess) {
    toast({
      title: `Success`,
      description: `${action} completed successfully`,
      variant: "default",
    });
  }
  
  return { success: true, data, error: null };
};
